import { createActionGroup, emptyProps, props } from '@ngrx/store';
import { Todo, TodoFilter } from '../../models/todo.model';

/**
 * `createActionGroup` generates a namespaced set of action creators.
 * Each event below becomes `TodoActions.eventName({ ...props })`.
 */
export const TodoActions = createActionGroup({
  source: 'Todo',
  events: {
    // Dispatched once on app start: kicks off the "load from storage or seed from API" effect.
    'Init': emptyProps(),
    'Load Todos Success': props<{ todos: Todo[] }>(),
    'Load Todos Failure': props<{ error: string }>(),

    // User-driven CRUD events. The id/createdAt are generated by the caller
    // (not the reducer) so the reducer stays a pure function of its inputs.
    'Add Todo': props<{ todo: Todo }>(),
    'Remove Todo': props<{ id: string }>(),
    'Toggle Todo': props<{ id: string }>(),
    'Clear Completed': emptyProps(),

    // View-only state, still lives in the store so it's shareable/selectable.
    'Set Filter': props<{ filter: TodoFilter }>(),
  },
});
